// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'post.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_Post _$PostFromJson(Map<String, dynamic> json) => _Post(
  id: (json['id'] as num).toInt(),
  tags: json['tags'] as String? ?? null,
  createdAt: (json['created_at'] as num?)?.toInt() ?? null,
  updatedAt: (json['updated_at'] as num?)?.toInt() ?? null,
  creatorId: (json['creator_id'] as num?)?.toInt() ?? null,
  approverId: (json['approver_id'] as num?)?.toInt() ?? null,
  author: json['author'] as String? ?? null,
  change: (json['change'] as num?)?.toInt() ?? null,
  source: json['source'] as String? ?? null,
  score: (json['score'] as num?)?.toInt() ?? null,
  md5: json['md5'] as String? ?? null,
  fileSize: (json['file_size'] as num?)?.toInt() ?? null,
  fileExt: json['file_ext'] as String? ?? null,
  fileUrl: json['file_url'] as String? ?? null,
  isShownInIndex: json['is_shown_in_index'] as bool? ?? null,
  previewUrl: json['preview_url'] as String? ?? null,
  previewWidth: (json['preview_width'] as num?)?.toInt() ?? null,
  previewHeight: (json['preview_height'] as num?)?.toInt() ?? null,
  actualPreviewWidth: (json['actual_preview_width'] as num?)?.toInt() ?? null,
  actualPreviewHeight: (json['actual_preview_height'] as num?)?.toInt() ?? null,
  sampleUrl: json['sample_url'] as String? ?? null,
  sampleWidth: (json['sample_width'] as num?)?.toInt() ?? null,
  sampleHeight: (json['sample_height'] as num?)?.toInt() ?? null,
  sampleFileSize: (json['sample_file_size'] as num?)?.toInt() ?? null,
  jpegUrl: json['jpeg_url'] as String? ?? null,
  jpegWidth: (json['jpeg_width'] as num?)?.toInt() ?? null,
  jpegHeight: (json['jpeg_height'] as num?)?.toInt() ?? null,
  jpegFileSize: (json['jpeg_file_size'] as num?)?.toInt() ?? null,
  rating: json['rating'] as String? ?? null,
  isRatingLocked: json['is_rating_locked'] as bool? ?? null,
  hasChildren: json['has_children'] as bool? ?? null,
  parentId: (json['parent_id'] as num?)?.toInt() ?? null,
  status: json['status'] as String? ?? null,
  isPending: json['is_pending'] as bool? ?? null,
  width: (json['width'] as num?)?.toInt() ?? null,
  height: (json['height'] as num?)?.toInt() ?? null,
  isHeld: json['is_held'] as bool? ?? null,
  framesPendingString: json['frames_pending_string'] as String? ?? null,
  isNoteLocked: json['is_note_locked'] as bool? ?? null,
  lastNotedAt: (json['last_noted_at'] as num?)?.toInt() ?? null,
  lastCommentedAt: (json['last_commented_at'] as num?)?.toInt() ?? null,
);

Map<String, dynamic> _$PostToJson(_Post instance) => <String, dynamic>{
  'id': instance.id,
  'tags': instance.tags,
  'created_at': instance.createdAt,
  'updated_at': instance.updatedAt,
  'creator_id': instance.creatorId,
  'approver_id': instance.approverId,
  'author': instance.author,
  'change': instance.change,
  'source': instance.source,
  'score': instance.score,
  'md5': instance.md5,
  'file_size': instance.fileSize,
  'file_ext': instance.fileExt,
  'file_url': instance.fileUrl,
  'is_shown_in_index': instance.isShownInIndex,
  'preview_url': instance.previewUrl,
  'preview_width': instance.previewWidth,
  'preview_height': instance.previewHeight,
  'actual_preview_width': instance.actualPreviewWidth,
  'actual_preview_height': instance.actualPreviewHeight,
  'sample_url': instance.sampleUrl,
  'sample_width': instance.sampleWidth,
  'sample_height': instance.sampleHeight,
  'sample_file_size': instance.sampleFileSize,
  'jpeg_url': instance.jpegUrl,
  'jpeg_width': instance.jpegWidth,
  'jpeg_height': instance.jpegHeight,
  'jpeg_file_size': instance.jpegFileSize,
  'rating': instance.rating,
  'is_rating_locked': instance.isRatingLocked,
  'has_children': instance.hasChildren,
  'parent_id': instance.parentId,
  'status': instance.status,
  'is_pending': instance.isPending,
  'width': instance.width,
  'height': instance.height,
  'is_held': instance.isHeld,
  'frames_pending_string': instance.framesPendingString,
  'is_note_locked': instance.isNoteLocked,
  'last_noted_at': instance.lastNotedAt,
  'last_commented_at': instance.lastCommentedAt,
};
